name: resident_management
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  excel: ^4.0.6
  file_picker: ^10.3.8
  flutter:
    sdk: flutter
  
  http: ^1.6.0
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true